[package]
name = "fnntw"
version = "0.1.0"
description = "A short description of my package"
authors = ["Cavey Cool <caveycool@gmail.com>"]
repository = "https://github.com/cavemanloverboy/fnstw"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = []
timing = []
single_ref = []

[dependencies]
ordered-float = "3.0.0"
parking_lot = "0.12.1"
num-format = "0.4.0"

[profile.release]
lto = "fat"
codegen-units = 1

[dev-dependencies]
concat-idents = "1.1.3"
seq-macro = "0.3.1"
dry = "0.1.1"
rand = "0.8.5"
criterion = "0.3.6"
pdqselect = "0.1.1"
adqselect = "0.1.3"
rayon = "1.5.3"
ndarray = "0.15.6"
approx_eq = "0.1.8"
ndarray-npy = "0.8.1"

[[bench]]
name = "build"
harness = false

[[bench]]
name = "build_nc" # nc stands for no criterion
harness = false

[[bench]]
name = "medians"
harness = false

[[bench]]
name = "euclidean"
harness = false

[[bench]]
name = "query"
harness = false


