[package]
name = "fnstw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = []
timing = []

[dependencies]
ordered-float = "3.0.0"
parking_lot = "0.12.1"
num-format = "0.4.0"


[dev-dependencies]
concat-idents = "1.1.3"
seq-macro = "0.3.1"
dry = "0.1.1"
rand = "0.8.5"
criterion = "0.3.6"
pdqselect = "0.1.1"
adqselect = "0.1.3"


[[bench]]
name = "build"
harness = false

[[bench]]
name = "build_nc"
harness = false

[[bench]]
name = "medians"
harness = false

